name: Deploy Web Development
on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Web Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git fetch origin
          git checkout development
          git pull origin development

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new,feat,feature"
          major-wording: "MAJOR,cut-major"
          patch-wording: "patch,fixes,fix,adjust"
          rc-wording: "RELEASE,alpha"
          target-branch: "development"
          commit-message: "CI: bumps version to {{version}} [skip ci]"

      - name: yarn install
        run: yarn install

      - uses: culshaw/read-package-node-version-actions@v1
        id: package-json

      - name: Show version number
        run: echo "${{ steps.package-json.outputs.version }}"

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Create .env file"
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo STAGE=production >> .env
          echo HTTP_PORT=3000 >> .env
          echo APP_NAME=Artamananda >> .env
          echo APP_VERSION=${{ steps.package-json.outputs.version }} >> .env
          echo APP_URL=artamananda.my.id >> .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo STORAGE_URL=${{ secrets.STORAGE_URL }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env

      - name: Fetch SSH Host from API
        id: fetch_ssh_host
        run: |
          # Get the IP from the API response
          IP_ADDRESS=$(curl -s https://info.artamananda.my.id/my-ip | jq -r '.payload')

          # Check if the IP is IPv6 or IPv4
          if [[ $IP_ADDRESS =~ : ]]; then
            IPV6="[$IP_ADDRESS]"
            echo "IPv6 detected: $IP_ADDRESS. Continuing the process."
            echo "SSH_HOST=$IP_ADDRESS" >> $GITHUB_ENV
            echo "SSH_HOST_V6=$IPV6" >> $GITHUB_ENV
          else
            echo "IPv4 detected: $IP_ADDRESS. Stopping the process."
            exit 0  # Exit the workflow if it's IPv4
          fi

      - name: Build
        env:
          CI: false
        run: |
          yarn build

      - uses: vimtor/action-zip@v1.1
        with:
          files: .,!node_modules
          recursive: false
          dest: build.zip

      - name: Upload Build
        run: |
          curl -X POST \
            -F "file=@build.zip" \
            -F "target=/home/arta/artamananda-my-id" \
            https://action.artamananda.my.id/upload

      # - name: Upload to Server using SCP
      #   run: |
      #     # Set up SSH key for passwordless login (you can skip this step if you're using a password)
      #     mkdir -p ~/.ssh
      #     # echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      #     # chmod 600 ~/.ssh/id_rsa
      #     # Disable strict host checking for automatic connections
      #     echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" > ~/.ssh/config

      #     # Upload the files using SCP (excluding "node_modules")
      #     sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --exclude 'node_modules' ./ ${{ secrets.SSH_USER }}@${{ env.SSH_HOST_V6 }}:/home/arta/artamananda-my-id

      # - name: Upload to Server
      #   uses: nogsantos/scp-deploy@master
      #   with:
      #     host: ${{ env.SSH_HOST_V6 }}
      #     user: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     # Selecting all folders except "node_modules"
      #     src: ".,!node_modules"
      #     # The path is based on the directory where the user logged into the server starts
      #     remote: "/home/arta/artamananda-my-id"
      #     # rm: true

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          protocol: tcp6
          port: 22
          script: |
            cd /home/arta/artamananda-my-id
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            yarn install
            pm2 delete artamananda-my-id
            pm2 start
