name: Deploy Web Development
on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Web Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new,feat,feature"
          major-wording: "MAJOR,cut-major"
          patch-wording: "patch,fixes,fix,adjust"
          rc-wording: "RELEASE,alpha"
          target-branch: "main"
          commit-message: "CI: bumps version to {{version}} [skip ci]"

      - uses: culshaw/read-package-node-version-actions@v1
        id: package-json

      - name: Show version number
        run: echo "${{ steps.package-json.outputs.version }}"

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Create .env file"
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo STAGE=production >> .env
          echo HTTP_PORT=3000 >> .env
          echo APP_NAME=Artamananda >> .env
          echo APP_VERSION=${{ steps.package-json.outputs.version }} >> .env
          echo APP_URL=artamananda.my.id >> .env
          echo BASE_API_URL=${{ secrets.BASE_API_URL }} >> .env
          echo STORAGE_URL=${{ secrets.STORAGE_URL }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
